// Example: wiring a multi-variant (themed) screen + a theme switch.
// Adapt paths to the host project. Assumes Vite (import.meta.glob) + the bundled
// SceneRenderer copied into the project's components.

// ─────────────────────────────────────────────────────────────────────────────
// 1) The screen component — one scene per theme variant, picked by themeId.
//    Generated by: build-section-scene.mjs <unpack> "<frame 17>" <img> scenes/theme1.json
//                  ...once per variant (17..22 → theme1..theme6)
// ─────────────────────────────────────────────────────────────────────────────
import { SceneRenderer, type Scene } from '../../components/SceneRenderer/SceneRenderer'

// Bundle every exported asset; resolve a scene `src` filename → URL.
const assetUrls = import.meta.glob('../../assets/moonfestival/img/*', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>
const byName: Record<string, string> = {}
for (const [path, url] of Object.entries(assetUrls)) byName[path.split('/').pop()!] = url

// One scene per theme variant, keyed by file stem.
const sceneModules = import.meta.glob('./scenes/*.json', { eager: true }) as Record<
  string,
  { default: Scene }
>
const sceneByTheme: Record<string, Scene> = {}
for (const [path, mod] of Object.entries(sceneModules)) {
  sceneByTheme[path.split('/').pop()!.replace('.json', '')] = mod.default
}

const DEFAULT_THEME = 'theme1'

export function MoonFestival({
  className,
  themeId = DEFAULT_THEME,
}: {
  className?: string
  themeId?: string
}) {
  const scene = sceneByTheme[themeId] ?? sceneByTheme[DEFAULT_THEME]
  return <SceneRenderer scene={scene} assetUrl={(src) => byName[src]} className={className} />
}

// ─────────────────────────────────────────────────────────────────────────────
// 2) App shell — page tabs + a shared theme switch.
//    Each Moon Festival variant maps to a theme by matching its accent colour
//    (verify the mapping by reading the per-variant label fill from the export).
// ─────────────────────────────────────────────────────────────────────────────
//
// const THEMES = [
//   { id: 'theme1', accent: '#81ccd1' }, { id: 'theme2', accent: '#62b4ff' },
//   { id: 'theme3', accent: '#985de9' }, { id: 'theme4', accent: '#fc8aa3' },
//   { id: 'theme5', accent: '#807aff' }, { id: 'theme6', accent: '#9a41fe' },
// ]
//
// function App() {
//   const [themeId, setThemeId] = useState('theme1')
//   return (
//     <>
//       <ThemeSwitcher value={themeId} onChange={setThemeId} themes={THEMES} />
//       <MoonFestival themeId={themeId} className="mx-auto w-[390px]" />
//     </>
//   )
// }
//
// Note: the scene already bakes each variant's correct colours (text composited
// per-variant from the structure; decor assets per-theme via colorSig). The
// themeId only selects WHICH scene to show — no CSS recolour is applied, because
// multi-theme Figma sections are distinct palettes, not one swappable accent.
